#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

name: release
on:
  push:
    tags:
      - 'v*'
jobs:
  publish:
    name: Publish image
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
        id: go

      - name: Set ENV vars
        run: |
          TAG=$(git describe --tags --always `git rev-list --tags --max-count=1`)
          echo "IMAGE_TAG"=$TAG >> $GITHUB_ENV
          echo "DID_RESOLVER_IMAGE_PREFIX"=ghcr.io/trustbloc/did-resolver >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.CR_USER }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and Push container did resolver image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./images/did-rest/Dockerfile
          platforms: linux/amd64,linux/arm64
          build-args: |
            ALPINE_VER=3.15
            GO_VER=1.17
          push: true
          tags: |
            ${{ env.DID_RESOLVER_IMAGE_PREFIX }}:${{ env.IMAGE_TAG }}
            ${{ env.DID_RESOLVER_IMAGE_PREFIX }}:latest
